# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:experimental
FROM python:3.10-slim

# Set workdir
WORKDIR /app

# Copy pyproject and install build dependencies first
COPY pyproject.toml .

# Install runtime dependencies
RUN pip install --no-cache-dir uv uv-build httpx beautifulsoup4 python-dotenv mcp-server

# Copy application source
COPY . .

# Expose port if any (FastMCP default is stdio)
# No port exposure needed for stdio-based MCP

# Set entrypoint
CMD ["python", "main.py"]
